package de.neuefische.backend.service;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.junit.jupiter.MockitoExtension;

import java.time.LocalDateTime;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.*;

@ExtendWith(MockitoExtension.class)
class AutoGeneratedValuesServiceTest {

    @InjectMocks
    AutoGeneratedValuesService mockAutoGeneratedValuesService;

    @Test
    void generateRandomId() {
        //GIVEN
        String expected = UUID.randomUUID().toString();
        //WHEN
        String actual = mockAutoGeneratedValuesService.generateRandomId();
        //THEN
     assertNotEquals(expected, actual);
    }

    @Test
    void currentLocalDateTime() {
        //GIVEN
        LocalDateTime expected = LocalDateTime.now();
        //WHEN
        LocalDateTime actual = mockAutoGeneratedValuesService.currentLocalDateTime();
        //THEN
        assertNotEquals(expected, actual);
    }

    @Test
    void getCategory() {
        //GIVEN
        String expected = "Regular";
        //WHEN
        String actual = mockAutoGeneratedValuesService.getCategory();
        //THEN
        assertEquals(expected, actual);
    }
}