package de.neuefische.backend.service;

import org.springframework.stereotype.Service;

import java.time.LocalDateTime;
import java.util.UUID;

@Service
public class AutoGeneratedValuesService {

private final IngredientService ingredientService;
    public AutoGeneratedValuesService(IngredientService ingredientService) {
        this.ingredientService = ingredientService;
    }


    public String generateRandomId() {
        return UUID.randomUUID().toString();
    }
    public LocalDateTime currentLocalDateTime() {
        return LocalDateTime.now();
    }

    public String getCategory(String requestMessage) {
        return ingredientService.sendGptRequest(requestMessage);
    }
}
