package de.neuefische.backend.service;
import de.neuefische.backend.dto.RecipeDto;
import de.neuefische.backend.exceptions.RecipeNotFoundException;
import de.neuefische.backend.model.Ingredient;
import de.neuefische.backend.model.Recipe;
import de.neuefische.backend.repository.RecipeRepository;
import org.springframework.stereotype.Service;

import javax.lang.model.element.Name;
import java.time.LocalDateTime;
import java.util.*;
import java.util.stream.Collectors;

@Service
public class RecipeService {
    private final RecipeRepository recipeRepo;
    private final AutoGeneratedValuesService autoGeneratedValuesService;

    public RecipeService(RecipeRepository recipeRepo, AutoGeneratedValuesService autoGeneratedValuesService) {
        this.recipeRepo = recipeRepo;
        this.autoGeneratedValuesService = autoGeneratedValuesService;
    }

    public List<Recipe> getAllRecipes() {
        return recipeRepo.findAll();
    }


    public Recipe addRecipe(RecipeDto recipeDto) {
        String ingredientNames = recipeDto.ingredients().stream()
                .map(Ingredient::name)  // get the name field
                .collect(Collectors.joining(", ")); // join with comma

        String id = autoGeneratedValuesService.generateRandomId();

        LocalDateTime createdAt = autoGeneratedValuesService.currentLocalDateTime();
        String foodCategory = autoGeneratedValuesService.getCategory(ingredientNames);
        Recipe recipeToSave = recipeDto.createNewRecipe(id, createdAt, foodCategory);

        return recipeRepo.save(recipeToSave);
    }

    public Recipe getRecipeById(String id) {
        return recipeRepo
                .findById(id)
                .orElseThrow(() -> new RecipeNotFoundException("Recipe with the id: " + id + " not found!"));
    }

    public Recipe updateRecipeById(String id, RecipeDto updatedRecipeDto) {
        String ingredientNames = updatedRecipeDto.ingredients().stream()
                .map(Ingredient::name)  // get the name field
                .collect(Collectors.joining(", ")); // join with comma

        String foodCategory = autoGeneratedValuesService.getCategory(ingredientNames);

        Recipe recipeToUpdate = getRecipeById(id);

        Recipe updatedRecipe = updatedRecipeDto.
                    createNewRecipe(recipeToUpdate.id(), recipeToUpdate.createdAt(), foodCategory);
        return recipeRepo.save(updatedRecipe);

    }

    public void deleteRecipeById(String id) {
        if (!recipeRepo.existsById(id)) {
            throw new RecipeNotFoundException("Recipe with the id: " + id + " not found!");
        }
        recipeRepo.deleteById(id);
    }
}

