package de.neuefische.backend.service;

import de.neuefische.backend.dto.RecipeDto;
import de.neuefische.backend.model.Recipe;
import de.neuefische.backend.repository.RecipeRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;
import java.util.*;


@Service
public class RecipeService {
    private final RecipeRepository recipeRepo;
    private final AutoGeneratedValuesService autoGeneratedValuesService;

    public RecipeService(RecipeRepository recipeRepo, AutoGeneratedValuesService autoGeneratedValuesService) {
        this.recipeRepo = recipeRepo;
        this.autoGeneratedValuesService = autoGeneratedValuesService;
    }

    public List<Recipe> getAllRecipes() {
        return recipeRepo.findAll();
    }


    public Recipe addRecipe(RecipeDto recipeDto) {
        String id = autoGeneratedValuesService.generateRandomId();
        LocalDateTime createdAt = autoGeneratedValuesService.currentLocalDateTime();
        String category = autoGeneratedValuesService.getCategory();
        Recipe recipeToSave = recipeDto.createNewRecipe(id, createdAt, category);
        return recipeRepo.save(recipeToSave);
    }
}

